name: checkstyle

on:
  pull_request:
    branches: [ main ]

jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dbelyaev/action-checkstyle@v0.5.1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
            version: v1.29
            args: --enable=golint,bodyclose,gosec,whitespace
      - uses: reviewdog/action-setup@v1
        with:
            reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          golint ./... | reviewdog -f=golint -reporter=github-pr-check